general_cfg = {
    'zbins': 10,
    'nbl': 30,
    'triu_or_tril': 'triu',
    'row_col': 'row',
    'ell_recipe': 'ISTF',
    'probes': ('3x2pt',),
    'which_NGs': ('SSC', 'cNG'),
    'save_covs': True,
    'hm_recipe': 'Krause2017',
    'GL_or_LG': 'GL',
    'ell_min': 10,
    'ell_max': 5000,
    'use_ray': False,
}
